version: '3'

services:
  # Game server
  server:
    image: ${TLBB_SERVER_IMAGE_NAME}:v0.1
    volumes:
      - "${SERVER_DIR}/server:/home"
    ports:
      - "${LOGIN_PORT}:${LOGIN_PORT}"
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "${BILLING_PORT}:${BILLING_PORT}"
    restart: always
    links:
      - tlbbdb
      - webdb
  # Game database
  tlbbdb:
    image: ${TLBBDB_IMAGE_NAME}:v0.1
    volumes:
      - "${SERVER_DIR}/tlbbdb/mysql:/var/lib/mysql"
    ports:
      - "${TLBB_MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${TLBB_MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "tlbbdb"
    restart: always
  # Web database
  webdb:
    image: ${WEBDB_IMAGE_NAME}:v0.1
    volumes:
    - "${SERVER_DIR}/webdb/mysql:/var/lib/mysql"
    ports:
    - "${WEB_MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${WEB_MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "web"
    restart: always
  # docker管理监控
  portainer:
    image: portainer/portainer:latest
    ports:
      - "${PORTAINER_PORT}:9000" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PORTAINER_CN}:/public
    restart: always